
const.D_rodinhas = 0.135;
const.dens_balsa=73.5;   %164.4736842;                                      %densidade da balsa [kg/m^3]
const.dens_divinycell=60;  %51.87260089;                                    %densidade do divinycell   [kg/m^3]
const.dens_carbono=1600;  %1021.390742;                                     %densidade do carbono   [kg/m^3]
const.dens_aluminio=2810;                                                   %densidade do aluminio  [kg/m^3]
const.dens_ent=0.026858304;                                                 %densidade do material usado na entelagem [kg/m^2]                    (EM ÁREA)
const.dens_tubinho=1564.2051;                                               %densidade do tubinho de carbono  [kg/m^3]
const.E_balsa1=2.04;   %3.4;                                                %E da balsa no sentido da fibra (GPa)
const.E_balsa2=0.028;                                                       %E da balsa normal à fibra (GPa)
const.E_divinycell=0.075;                                                   %E do divinycell (GPa)
const.E_carbono1= 51.1;  %70;                                               %E do carbono no sentido da fibra (GPa)
const.E_carbono2=51.1;   %70;                                               %E do carbono no sentido normal à fibra (GPa)
const.E_aluminio=71.1;                                                      %E do alumínio (GPa)
const.G_balsa1=1200;                                                        %G da balsa no sentido da fibra (MPa)
const.G_balsa2=10;                                                          %G da balsa normal à fibra (MPa)
const.G_divinycell=20;                                                      %G do divinycell (MPa)
const.G_carbono1=5000;                                                      %G do carbono no sentido da fibra (MPa)
const.G_carbono2=5000;                                                      %G do carbono normal à fibra (MPa)
const.G_aluminio=26900;                                                     %G do alumínio (MPa) 
const.comp_balsa1=12.6;                                                     %sigma_comp da balsa no sentido da fibra (MPa)
const.comp_balsa2=0.7;                                                      %sigma_comp da balsa normal à fibra (MPa)
const.comp_divinycell=0.9;                                                  %sigma_comp do divinycell (MPa)
const.comp_carbono1=400;   %570;                                            %sigma_comp do carbono no sentido da fibra (MPa)
const.comp_carbono2=400;   %570;                                            %sigma_comp do carbono normal à fibra (MPa)
const.comp_aluminio=572;                                                    %sigma_comp do aluminio (MPa)
const.tra_balsa1=14.3;                                                      %sigma_tra da balsa no sentido da fibra (MPa)
const.tra_balsa2=0.8;                                                       %sigma_tra da balsa normal à fibra (MPa)
const.tra_divinycell=1.8;                                                   %sigma_tra do divinycell (MPa)
const.tra_carbono1=450;   %600;                                             %sigma_tra do carbono no sentido da fibra (MPa)
const.tra_carbono2=450;   %600;                                             %sigma_tra do carbono normal à fibra (MPa)
const.tra_aluminio=572;                                                     %sigma_tra do aluminio (MPa)
const.tau_balsa1=3.1;                                                       %tau da balsa no sentido da fibra (MPa)
const.tau_balsa2=3.1;                                                       %tau da balsa normal à fibra (MPa)
const.tau_divinycell=0.76;                                                  %tau do divinycell (MPa)
const.tau_carbono1=60;                                                      %tau do carbono no sentido da fibra (MPa)
const.tau_carbono2=60;                                                      %tau do carbono normal à fibra (MPa)
const.tau_aluminio=331;                                                     %tau do aluminio (MPa)
%const.m_servo=;                                                             %massa do servo (kg)
const.m_helice=0.0538;                                                      %massa da hélice (kg)
const.m_tanque=0.0305;                                                      %massa do tanque (kg)

